import type { CommandCenterSnapshot } from "@/lib/types";

export function getMockCommandCenterSnapshot(): CommandCenterSnapshot {
  const now = Date.now();

  return {
    mode: "empty",
    generatedAt: new Date(now).toISOString(),
    metrics: [
      {
        label: "Usuarios monitorados",
        value: "128",
        delta: "+12 esta semana",
        hint: "Perfis com onboarding concluido e atividade recente.",
        tone: "good",
      },
      {
        label: "Pendencias de sync",
        value: "17",
        delta: "-8 vs ontem",
        hint: "Fila local aguardando sincronizacao com Supabase.",
        tone: "warning",
      },
      {
        label: "Frota operacional",
        value: "99.94%",
        delta: "1 nodo degradado",
        hint: "Android, Windows e Command Center acompanhados por heartbeat.",
        tone: "good",
      },
      {
        label: "Incidentes criticos",
        value: "2",
        delta: "1 em investigacao",
        hint: "Alertas que exigem acao da operacao ainda hoje.",
        tone: "critical",
      },
    ],
    activity: [
      { label: "Seg", sessions: 39, activeUsers: 18, syncBacklog: 12, errors: 1 },
      { label: "Ter", sessions: 42, activeUsers: 21, syncBacklog: 9, errors: 1 },
      { label: "Qua", sessions: 51, activeUsers: 25, syncBacklog: 14, errors: 2 },
      { label: "Qui", sessions: 56, activeUsers: 27, syncBacklog: 11, errors: 0 },
      { label: "Sex", sessions: 49, activeUsers: 24, syncBacklog: 16, errors: 2 },
      { label: "Sab", sessions: 62, activeUsers: 31, syncBacklog: 19, errors: 3 },
      { label: "Dom", sessions: 46, activeUsers: 22, syncBacklog: 17, errors: 1 },
    ],
    fleet: [
      {
        id: "fleet-android",
        label: "CodeTrail Tablet",
        platform: "android",
        status: "up",
        version: "1.1.0",
        environment: "production",
        lastSeenAt: new Date(now - 1000 * 60 * 3).toISOString(),
        activeUsers: 83,
        pendingSync: 14,
        uptimePercent: 99.94,
      },
      {
        id: "fleet-windows",
        label: "CodeTrail Windows",
        platform: "windows",
        status: "up",
        version: "1.1.0",
        environment: "production",
        lastSeenAt: new Date(now - 1000 * 60 * 2).toISOString(),
        activeUsers: 27,
        pendingSync: 3,
        uptimePercent: 99.7,
      },
      {
        id: "fleet-web",
        label: "Command Center",
        platform: "web",
        status: "up",
        version: "0.1.0",
        environment: "production",
        lastSeenAt: new Date(now - 1000 * 20).toISOString(),
        activeUsers: 4,
        pendingSync: 0,
        uptimePercent: 100,
      },
      {
        id: "fleet-api",
        label: "Telemetry ingest",
        platform: "api",
        status: "degraded",
        version: "0.1.0",
        environment: "production",
        lastSeenAt: new Date(now - 1000 * 60 * 5).toISOString(),
        activeUsers: 0,
        pendingSync: 0,
        uptimePercent: 97.8,
      },
    ],
    platforms: [
      {
        platform: "android",
        instances: 1,
        uniqueVersions: 1,
        activeUsers: 83,
        pendingSync: 14,
        degradedNodes: 0,
        latestSeenAt: new Date(now - 1000 * 60 * 3).toISOString(),
      },
      {
        platform: "windows",
        instances: 1,
        uniqueVersions: 2,
        activeUsers: 27,
        pendingSync: 3,
        degradedNodes: 1,
        latestSeenAt: new Date(now - 1000 * 60 * 2).toISOString(),
      },
      {
        platform: "web",
        instances: 1,
        uniqueVersions: 1,
        activeUsers: 4,
        pendingSync: 0,
        degradedNodes: 0,
        latestSeenAt: new Date(now - 1000 * 20).toISOString(),
      },
      {
        platform: "api",
        instances: 1,
        uniqueVersions: 1,
        activeUsers: 0,
        pendingSync: 0,
        degradedNodes: 1,
        latestSeenAt: new Date(now - 1000 * 60 * 5).toISOString(),
      },
    ],
    releases: [
      {
        id: "android:1.1.0",
        platform: "android",
        version: "1.1.0",
        instances: 1,
        activeUsers: 83,
        pendingSync: 14,
        health: "up",
        environments: ["production"],
        lastSeenAt: new Date(now - 1000 * 60 * 3).toISOString(),
      },
      {
        id: "windows:1.1.0",
        platform: "windows",
        version: "1.1.0",
        instances: 1,
        activeUsers: 27,
        pendingSync: 3,
        health: "up",
        environments: ["production"],
        lastSeenAt: new Date(now - 1000 * 60 * 2).toISOString(),
      },
      {
        id: "windows:1.0.9",
        platform: "windows",
        version: "1.0.9",
        instances: 1,
        activeUsers: 0,
        pendingSync: 0,
        health: "degraded",
        environments: ["staging"],
        lastSeenAt: new Date(now - 1000 * 60 * 4).toISOString(),
      },
      {
        id: "web:0.1.0",
        platform: "web",
        version: "0.1.0",
        instances: 1,
        activeUsers: 4,
        pendingSync: 0,
        health: "up",
        environments: ["production"],
        lastSeenAt: new Date(now - 1000 * 20).toISOString(),
      },
      {
        id: "api:0.1.0",
        platform: "api",
        version: "0.1.0",
        instances: 1,
        activeUsers: 0,
        pendingSync: 0,
        health: "degraded",
        environments: ["production"],
        lastSeenAt: new Date(now - 1000 * 60 * 5).toISOString(),
      },
    ],
    systems: [
      {
        id: "sys-01",
        machineName: "BIEL-STUDIO",
        status: "up",
        appVersion: "1.1.0",
        cpuPercent: 28,
        memoryPercent: 61,
        diskPercent: 48,
        networkStatus: "online",
        lastSeenAt: new Date(now - 1000 * 60 * 2).toISOString(),
        appUptimeHours: 9.4,
        osUptimeHours: 36.2,
        environment: "production",
      },
      {
        id: "sys-02",
        machineName: "NOTEBOOK-CODE",
        status: "degraded",
        appVersion: "1.1.0",
        cpuPercent: 82,
        memoryPercent: 73,
        diskPercent: 69,
        networkStatus: "limited",
        lastSeenAt: new Date(now - 1000 * 60 * 8).toISOString(),
        appUptimeHours: 5.1,
        osUptimeHours: 18.9,
        environment: "production",
      },
      {
        id: "sys-03",
        machineName: "SUPPORT-LAB",
        status: "up",
        appVersion: "1.0.9",
        cpuPercent: 34,
        memoryPercent: 49,
        diskPercent: 38,
        networkStatus: "online",
        lastSeenAt: new Date(now - 1000 * 60 * 4).toISOString(),
        appUptimeHours: 11.8,
        osUptimeHours: 51.4,
        environment: "staging",
      },
    ],
    users: [
      {
        id: "6ce815fd-6baf-4f3b-a9eb-1e8e29b9cb26",
        name: "Marina Costa",
        email: "marina@codetrail.dev",
        desiredArea: "Data Engineer",
        trackName: "Data Engineer",
        onboardingCompleted: true,
        lastSeenAt: new Date(now - 1000 * 60 * 18).toISOString(),
        activeStreak: 6,
        weeklyHours: 8.5,
        pendingSync: 0,
        riskLevel: "healthy",
        supportStatus: "stable",
        internalNote: "Alto engajamento e nenhuma falha recente.",
        nextActionAt: null,
      },
      {
        id: "53813ca3-fce8-4c73-a52f-5005a8ddb13d",
        name: "Rafael Nunes",
        email: "rafael@codetrail.dev",
        desiredArea: "Backend Python",
        trackName: "Backend Python",
        onboardingCompleted: true,
        lastSeenAt: new Date(now - 1000 * 60 * 90).toISOString(),
        activeStreak: 4,
        weeklyHours: 6.2,
        pendingSync: 7,
        riskLevel: "attention",
        supportStatus: "monitoring",
        internalNote: "Fila de sync voltou a subir no tablet principal.",
        nextActionAt: new Date(now + 1000 * 60 * 60 * 6).toISOString(),
      },
      {
        id: "f7b3fd17-f876-4246-b72f-4d934ff4eb98",
        name: "Lucas Araujo",
        email: "lucas@codetrail.dev",
        desiredArea: "DevOps",
        trackName: "DevOps",
        onboardingCompleted: true,
        lastSeenAt: new Date(now - 1000 * 60 * 60 * 7).toISOString(),
        activeStreak: 2,
        weeklyHours: 2.8,
        pendingSync: 13,
        riskLevel: "critical",
        supportStatus: "needs_follow_up",
        internalNote: "Windows agent com heartbeat intermitente e backlog de revisoes.",
        nextActionAt: new Date(now + 1000 * 60 * 60 * 2).toISOString(),
      },
      {
        id: "852f4967-ac6c-4d64-aa09-a8f4515eec1b",
        name: "Aline Souza",
        email: "aline@codetrail.dev",
        desiredArea: "Front-end React",
        trackName: "Front-end React",
        onboardingCompleted: true,
        lastSeenAt: new Date(now - 1000 * 60 * 32).toISOString(),
        activeStreak: 7,
        weeklyHours: 10.1,
        pendingSync: 2,
        riskLevel: "healthy",
        supportStatus: "stable",
        internalNote: "Concluiu projeto pratico ontem e manteve consistencia.",
        nextActionAt: null,
      },
    ],
    database: [
      {
        tableName: "profiles",
        label: "Perfis",
        rowCount: 128,
        description: "Base principal de usuarios com trilha e onboarding.",
        health: "healthy",
      },
      {
        tableName: "study_sessions",
        label: "Sessoes",
        rowCount: 2312,
        description: "Historico total de estudo registrado pelos apps.",
        health: "healthy",
      },
      {
        tableName: "tasks",
        label: "Tarefas",
        rowCount: 846,
        description: "Itens operacionais e de estudo ainda em circulacao.",
        health: "healthy",
      },
      {
        tableName: "reviews",
        label: "Revisoes",
        rowCount: 503,
        description: "Agenda de repeticao espaçada e revisoes pendentes.",
        health: "healthy",
      },
      {
        tableName: "study_notes",
        label: "Notas",
        rowCount: 412,
        description: "Anotacoes centralizadas vindas dos apps do usuario.",
        health: "healthy",
      },
      {
        tableName: "sync_queue",
        label: "Fila de sync",
        rowCount: 17,
        description: "Registros locais ainda nao enviados para o Supabase.",
        health: "attention",
      },
    ],
    incidents: [
      {
        id: "inc-01",
        severity: "critical",
        title: "Heartbeat do telemetry ingest oscilando",
        source: "Telemetry ingest",
        status: "investigating",
        openedAt: new Date(now - 1000 * 60 * 70).toISOString(),
        resolvedAt: null,
        summary:
          "A API de ingestao respondeu mais lentamente e deixou 3 heartbeats acumularem.",
        action: "Verificar logs do deploy e liberar nova rodada de retries.",
        context: { platform: "api", version: "0.1.0" },
      },
      {
        id: "inc-02",
        severity: "warning",
        title: "Fila de sync elevada em usuarios Windows",
        source: "CodeTrail Windows",
        status: "open",
        openedAt: new Date(now - 1000 * 60 * 34).toISOString(),
        resolvedAt: null,
        summary:
          "Usuarios com backlog acima de 10 itens foram concentrados em uma mesma versao do app.",
        action: "Cruzar backlog por versao e confirmar se a build 1.1.0 esta instalada.",
        context: { platform: "windows", version: "1.1.0" },
      },
      {
        id: "inc-03",
        severity: "info",
        title: "Crescimento acima do previsto em study_sessions",
        source: "Banco de dados",
        status: "mitigated",
        openedAt: new Date(now - 1000 * 60 * 180).toISOString(),
        resolvedAt: null,
        summary:
          "O pico era esperado pelo seed de testes e nao representa comportamento anomalo.",
        action: "Seguir apenas com observacao da taxa diaria.",
        context: { platform: "api", version: "0.1.0" },
      },
    ],
  };
}
